---
title: "DHS Anatomy"
author: "jp"
date: "October 1, 2015"
output: html_document
---

```{r, include = FALSE}
library(survey) 	# load survey package (analyzes complex design surveys)
library(foreign) 	# load foreign package (converts data files into R)
library(Hmisc)
library(ggplot2)
library(scales)
library(dplyr)
library(knitr)

# by default, R will crash if a primary sampling unit (psu) has a single observation
# set R to produce conservative standard errors instead of crashing
# http://r-survey.r-forge.r-project.org/survey/exmample-lonely.html
# by uncommenting this line:
options( survey.lonely.psu = "adjust" )
# this setting matches the MISSUNIT option in SUDAAN


# the r data.frame object can be loaded directly
# from your local hard drive,
# since the download script has already run

# load the 2004 malawi individual recodes data.frame object
load( "./Nigeria/Standard DHS 2013/Individual Recode.rda" )

# data is loaded as 'x'
```

The individual recode file has `r comma(nrow(x))` rows with `r comma(ncol(x))` variables.

```{r, echo=FALSE, results='markup', comment=''}
d = x[, 1:30]

describe(d)

# dd = describe(d)
# 
# latex( dd, type='html')

```

