---
title: "DHS data summary"
author: "jp"
date: "February 1, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, comment = "")

library(knitr)
library(dplyr)
library(countrycode)
```

```{r}
 load("survey_summaries.rda")
  
# function to list countries with non-missing data in a variable
nonMissingData = function( var = NA )
{
  dhs_clusters %>% filter_(paste('!is.na(', var, ')')) %>% count(country, survey_year)
}

# PMI 
pmi = c( "Angola", "Benin", "DRC", 
         "Ethiopia", "Ghana", "Guinea", "Kenya", "Liberia", "Madagascar", "Malawi", "Mali", "Mozambique", 
         "Nigeria", "Rwanda", "Senegal", "Tanzania", "Uganda", "Zambia", "Zimbabwe",
         
         "Burma", "Cambodia", "China (Yunnan Province)", "Lao People’s Democratic Republic", 
         "Thailand", "Viet Nam")

pmi_iso3 = countrycode(pmi, "country.name", "iso3c")

```


# At the time of this report, DHS data from the following countries was available from measures dhs  
## PMI

```{r }

dhs_clusters %>%  
  mutate( iso3c = countrycode(country, "country.name", "iso3c") ) %>%
  filter( iso3c %in% pmi_iso3) %>%
  inner_join(countrycode_data[, c("iso3c", "continent")]) %>%
  group_by(continent , country, survey_year) %>% summarise( clusters = n()) %>%
  count(continent , country) %>% 
  kable(row.names = TRUE)

```


## Non-PMI 

```{r }

dhs_clusters %>%  
  mutate( iso3c = countrycode(country, "country.name", "iso3c") ) %>%
  filter( !iso3c %in% pmi_iso3) %>%
  inner_join(countrycode_data[, c("iso3c", "continent")]) %>%
  group_by(continent , country, survey_year) %>% summarise( clusters = n()) %>%
  count(continent , country) %>% 
  kable(row.names = TRUE)

```


```{r }
nonMissingData("latitude") %>% kable( caption = "**Geocoded data** (n = number of clusters)", row.names = TRUE)
nonMissingData("hml32") %>% kable( caption = "**Microscopy malaria test**", row.names = TRUE) # slide
nonMissingData("hml32a") %>% kable( caption = "**Pf identification**",row.names = TRUE) # pf
nonMissingData("hml35") %>% kable( caption = "**RDT malaria test**" ,row.names = TRUE) # rdt
```

