---
title: "Survey Results"
output: html_document
runtime: shiny
---

```{r packages, echo=FALSE, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(DT)
   
library(survey)  
options(survey.lonely.psu="adjust")

library(ggplot2)
library(scales)
library(grid)
library(lubridate)
library(dplyr)


# base map
library(sp)
library(rworldmap) # this pkg has waaaay better world shapefiles
library(ggthemes)
library(ggmap); library(BH)

library(countrycode)

## location of DHS survey and code folders.
## include DHS files as: paste0( dhs_surveys, <dhs file here>)
survey_folder = "../DHS/_Surveys/"
code_folder = "../DHS/_Code/"
dataset_folder = "../DHS/_Datasets/"

```

```{r surveys}
# get list of surveys and files ####
source( paste0( code_folder , "file_list.r") )

subsahara = countrycode_data %>%
     filter( region %in% c("Middle Africa", "Western Africa", "Eastern Africa", "Southern Africa")) %>%
     rename( country.name = country.name.en) %>%
     select( country.name, iso3c ) %>%
     filter( !country.name %in% "Lesotho")


f = files %>%
     filter( year >= 2000 ) %>%
     # convert to standard country names in countrycode package, which
     # avoids having 'two' countries like Tanzania and United Republic of Tanzania
     mutate( country.name = countrycode(country, "country.name.en", "country.name.en")) %>%
     rename( Country = country.name ) %>%
     filter(Country %in% subsahara$country.name) %>%
     mutate( country.name = countrycode(country, "country.name.en", "country.name.en")) %>%
     filter( survey!="", year >= 2000 , country.name %in% subsahara$country.name) %>%
     mutate( iso3 = countrycode( country, 'country.name', "iso3c" ) ) %>%
    dplyr::count( country, country.name, iso3,  survey_year, year, survey ) 



# Chart of most recent survey ####
load("../malaria_atlas/africa_grid.rda")
#
# # PMI
pmi = c( "Angola", "Benin", "DRC",
         "Ethiopia", "Ghana", "Guinea", "Kenya", "Liberia", "Madagascar", "Malawi", "Mali", "Mozambique",
         "Nigeria", "Rwanda", "Senegal", "Tanzania", "Uganda", "Zambia", "Zimbabwe" )

pmi_iso3 = countrycode(pmi, "country.name", "iso3c")
#
last_survey = f %>% 
  mutate( iso3c= countrycode(country, "country.name", "iso3c") ) %>%
  group_by(iso3c) %>%
  summarise(year = max(year)) %>%
  right_join( africa_grid , by = "iso3c") %>% # hexbin map
  mutate( pmi = iso3c %in% pmi_iso3, 
          `last survey year` = ifelse( grepl( "2012|2013|2014|2015", year),
                                       "2012-2015",
                                       ifelse( grepl("2008|2009|2010|2011", year),
                                               "2008-2011",
                                              ifelse( !is.na(year), "<2008", NA)
                                              ) )
          ) 



                                       
```


```{r ui}

countries = f %>% count(country) %>% select(country) %>%
      unlist() %>% unname()

shinyUI( 
   fluidPage(
      # sidebarLayout(
      # sidebarPanel(
      inputPanel(
        
        selectInput("Country", label = "Country:", choices = countries, selected = "Angola"),
        
        selectInput("survey", label = "Survey", choices = c("")),
        
        textOutput("text1")
        
        )
# )
,

   # mainPanel( 
      tabsetPanel( 
         
         tabPanel(title = "Parasitemia", 
                  verbatimTextOutput("parasitemia"),
                  verbatimTextOutput("parasitemia.urban"),
                  verbatimTextOutput("parasitemia_by_age"),
                  plotOutput("parasitemia_by_age_plot")
                  ),
         tabPanel(title = "Net Ownership",
                  verbatimTextOutput("own_net"),
                  verbatimTextOutput("own_net_by_urbanRural")
         ),
         tabPanel(title = "Net Usage",
                  verbatimTextOutput("anynet"),
                  verbatimTextOutput("anynet.urban"),
                  verbatimTextOutput("anynet_by_age"),
                  plotOutput("anynet_by_region"),
                  verbatimTextOutput("itn"),
                  # print("slept under ITN^[includes persons
                  #       who respond sleep under 'Both treated and untreated bednets']
                  #       by age group"),
                  verbatimTextOutput("itn_by_age")
         ),
         tabPanel(title = "Mortality", verbatimTextOutput("mortality") ),
         tabPanel(title = "Respondents", verbatimTextOutput("respondents") ),
         tabPanel(title = "Data Structure", verbatimTextOutput("structure") ),
         tabPanel(title = "Data Dictionary", DT::dataTableOutput("dictionary"), 
                  width = "100%" ),
         tabPanel(title = "Map of Survey Dates", plotOutput(outputId = "main_plot",  width = "100%") ),

         type = 'tabs' 
         # ,
         # style = 'width: 100%; height: 100%'
      )
      
      # )
# )
))

# hexbin map of survey 'era'
output$main_plot =  
renderPlot({
 ggplot( data = last_survey) +
   geom_polygon(aes(x, y, group = id, fill = `last survey year`, alpha = pmi), size = 1) +
   scale_fill_manual( values = c("red", "orange", "yellow", "grey10")) +
    scale_alpha_manual( values = c(.5, 1)) +
   coord_fixed(ratio = 1) +
   geom_text(data = africa_grid_labels, aes(label = as.character(id), x= x, y = y), size = 3) +
    theme(line = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        panel.background = element_rect(colour = "blue", fill = "grey50")
        )
})


```

```{r survey_year_update}
observe({

      surveys = f %>%
      filter( country %in% input$Country) 
      
      surveys = surveys[rev(order(surveys$year)),]

      
      updateSelectInput(session, "survey",
                               choices = surveys$survey_year,
                               selected = surveys$survey_year[1]
                               )
})
```

```{r get_survey_functions}

# source( paste0( code_folder , "dhs_load_survey.R" ) )

source( paste0( code_folder, "getSurveyGIS.R") )
source( paste0( code_folder, 'load_survey_file.R' ) )


```

```{r variables}
library(readxl)

variable.doc = read_excel( paste0( code_folder, "dhs_variable_definitions.xlsx") 
                           )

individual_vars  = c(
   'hml32', 'hml35', # RDT and micrscopy
   'hml1', # number of mosquito bednets
   "hml4", # months ago net obtained.  (96 = more than 3 years ago; )
   "hml5", # net treated with insecticide when bought (e.g. ITN)
   "hml6", # net treatment status
   "hml7", # brand of bednet
   "hml8",  # net treated since receiving
   "hml9", # time since last retreatment
   "hml10" , # ITN
   "hml11" , # number of persons who slept under this net (5 = 5+, 9 = missing)
   "hml12", # type of net person slept under
   "hml19" , # person slept under an ever-treated net
   'hml20', # person slept under an llin

   'hv227', # has a bednet for sleeping
   'hv228', # children under 5 slept under bednet (e.g. all, some, none; 9 = missing )
   "hv253", # dwelling sprayed (some multiple responses)

   'hv102', # de jure member of household
   'hv103', # de facto memeber of household (slept there last night)
   'hml16', # corrected age in years (0:96)
   'hml16a' , # for children, corrected age in months

   "hv000", # country and phase
   "hv001", # cluster number
   "hv002", # household number
   'HV003', # line number of respondent answering questions
   'hv004' ,  # ultimate area unit ????
   'HV005', # household sample wieght (6 decimals )

   "HV021", # psu: enumeration area or sample cluster
   "HV005", # spample weight (divide by 1E6)
   "HV022", # Sample stratum number
   "hv023", # STRATA
   "hv024", # region
   "HV025" , # type of residence : urban rural

   'HHID', # case identification ????
   'HVIDX', # line number (1 to 90)
   "HV008", # date of interview
   "HV270", # wealth index
   "latitude", "longitude"
)

variables <- unique( tolower( individual_vars) )
variables = variables[ order(variables) ]


```

```{r svy} 
svy = reactive({
  
  if (is.null(input$Country) | is.null(input$survey)) {
    return(NULL)
  }    
  
country =  filter( f, country %in% input$Country & survey_year %in% input$survey) %>% .$country
year =  filter( f, country %in% input$Country & survey_year %in% input$survey) %>% .$year

# test.  not run.  
country =  filter( f, country %in% "Angola" & survey_year %in% "MIS 2011") %>% .$country
survey =  filter( f, country %in% "Angola" & survey_year %in% "MIS 2011") %>% .$survey
year =  filter( f, country %in% "Angola" & survey_year %in% "MIS 2011") %>% .$year

# load file
x = load_survey_file( .country = country,
                    .survey = survey ,
                    .year = year, 
                    vars = variables ,
                    geo = FALSE,
                    design = FALSE ,
                    dhs_code = code_folder ,
                    dhs_surveys = survey_folder
                    )

# transform variables as needed

# NB: all references to survey variable should be lower case (eg hv227, not HV227)
individual.mutate.nse = filter(
     variable.doc,
     !is.na(Code) ,
     Applies_to == "indiv",
     !(exclude %in% 1)
     ) %>%
     select(Variable, Code)  %>% as.list()

indiv = x %>%

     mutate_( .dots = setNames(
          individual.mutate.nse$Code ,
          individual.mutate.nse$Variable
     )  
     ) %>%
   mutate( rowid = row_number()) %>%  # use rowid when merging over results back into indiv
   ungroup()

  strataformula.hm = as.formula("~hv024 + hv025")
      
  svy <-
        svydesign(
          ~hv021  , # psu
          strata = strataformula.hm ,
          data =  indiv ,
          weights = ~ weight
        )

  svy =  update( svy,
               one = 1,
               age.grp = levels(addNA( # allows NA to be it own level
                 cut( hml16, breaks= c(0,5,15,25,35,45, Inf) ) ))
               )

return( svy )
})

# observe({
#   .country = input$Country
#   .survey_year = input$survey
#   
#   svy. = load_survey_object( .country = input$Country,
#                .survey_year = input$survey ,
#                geo = FALSE
#                )
# 
#   svy.h = svy.[[1]]
#   svy.c = svy.[[2]]
# })

```


```{r structure}


output$structure =  renderPrint({
  df = data.frame(Data = svy()[[3]], 
                row.names = names(svy()[[3]]))  
  # df = df[order(row.names(df)),]
  df
  })

```

```{r dictionary}
data_dictionary = readRDS( paste0( dataset_folder, 'dictionaryNew.rds') )

output$dictionary  = DT::renderDataTable({
  if ( is.null( svy()) ){ return()}
  
  dictionary = data_dictionary %>% filter(country == input$Country, 
                                          paste(survey,year) == input$survey)
                
  DT::datatable(dictionary, 
                options = list(orderClasses = TRUE, pageLength = 20))
  })

```

```{r respondents}

  svy.one = reactive({
  
    if ( is.null( svy()) ){ return()}

    svytotal( ~one , svy() )
  })

  output$respondents =  renderPrint({ 
    if ( is.null( svy()) ){ return() }
    svy.one()  
  })

```


```{r parasitemia}


svby_hml32. = reactive({
    svymean( ~ hml32 , svy() , na.rm = TRUE  )
})

output$parasitemia =  renderPrint({ 
  if ( is.null( svy()) ){ return() }
  svby_hml32.()  
  })

```

```{r parasitemia.urban}


svby_hml32.urban = reactive({
    svyby( ~ hml32 ,  ~hv025, svy() , svymean ,  na.rm = TRUE  )
})

output$parasitemia.urban =  renderPrint({ svby_hml32.urban()  })

```

```{r parasitemia_by_age}


svby_hml32_by_age = reactive({
  
  if ( is.null( svy()) ){ return()}
  
    svy_obj = svyby( ~ hml32 , ~ age.grp, svy(), svymean, na.rm = TRUE )
    return(svy_obj)
}) 

output$parasitemia_by_age =  renderPrint({ svby_hml32_by_age()  })

output$parasitemia_by_age_plot = renderPlot( 
  plot(svby_hml32_by_age(), main = "Parsitemia by Age Group")
                                             )
```


```{r ownnet}
svby_hml1.own = reactive({
  # svytable(~ hml12.anynet + v025, svy()[[1]], round=TRUE) 
  svymean( ~ hml1.own , svy()[[1]] , na.rm = TRUE  )
  # svyby( ~ hml12.anynet ,  ~ one, svy()[[1]] , svymean ,  na.rm = TRUE  )
})

output$own_net =  renderPrint({ svby_hml1.own() })
```

```{r own_net_by_urbanRural}
svby_hml1.own_net_by_urbanRural = reactive({
  # svytable(~ hml12.anynet + v025, svy()[[1]], round=TRUE) 
  svyby( ~ hml1.own ,  ~hv025, svy() , svymean ,  na.rm = TRUE  )
})

output$own_net_by_urbanRural =  renderPrint({ svby_hml1.own_net_by_urbanRural()  })
```

```{r anynet}
svby_hml12.anynet = reactive({
  # svytable(~ hml12.anynet + v025, svy()[[1]], round=TRUE) 
  svymean( ~ Any_net , svy() , na.rm = TRUE  )
  # svyby( ~ hml12.anynet ,  ~ one, svy()[[1]] , svymean ,  na.rm = TRUE  )
})

output$anynet =  renderPrint({ svby_hml12.anynet() })
```

```{r anynet_by_urbanRural}
svby_hml12.anynet.urban = reactive({
  # svytable(~ hml12.anynet + v025, svy()[[1]], round=TRUE) 
  svyby( ~ Any_net ,  ~hv025, svy() , svymean ,  na.rm = TRUE  )
})

output$anynet.urban =  renderPrint({ svby_hml12.anynet.urban()  })
```

```{r anynet_by_age}
svby_hml12.anynet_by_age = reactive({
  # svytable(~ hml12.anynet + v025, svy()[[1]], round=TRUE) 
  svyby( ~ Any_net ,  ~age.grp, svy() , svymean ,  na.rm = TRUE  )
})

output$anynet_by_age =  renderPrint({ svby_hml12.anynet_by_age()  })
```

```{r anynet_by_region}
svby_hml12.anynet_by_region = reactive({
  # svytable(~ hml12.anynet + v025, svy()[[1]], round=TRUE) 
  svyboxplot( Any_net ~ hv024, svy() , ylab = "Slept Under a Net" , xlab= 'Region' , na.rm = TRUE)
})

output$anynet_by_region =  renderPlot({ svby_hml12.anynet_by_region()  })
```

```{r itn}
svby_hml12.itn = reactive({
  # svytable(~ hml12.anynet + v025, svy()[[1]], round=TRUE) 
  confint(svymean( ~ hml12.itn ,  svy() ,  na.rm = TRUE  ))
})

output$itn =  renderPrint({ svby_hml12.itn()  })
```

```{r itn_by_age}
svby_hml12.itn_by_age = reactive({
  # svytable(~ hml12.anynet + v025, svy()[[1]], round=TRUE) 
  svyby( ~ hml12.itn ,  ~age.grp, svy() , svymean ,  na.rm = TRUE  )
})

output$itn_by_age =  renderPrint({ svby_hml12.itn_by_age()  })
```


```{r mort }
svby_b5 = reactive({
  
  if ( is.null( svy()) ){ return()}
  
    svyby( ~ b5 ,  ~hv025, svy() , svymean ,  na.rm = TRUE  )
})

output$mortality =  renderPrint({ svby_b5()  })

```

